data_input:
  all_data: 'data/raw/all-data.csv'
data_interim:
data_output:
model_input:
  rnd_seed: 21
  test_size: 0.20
  regularization_strength: 0.01
  class_weight: "balanced"
vectorizer_input:
  max_features: 4000
  ngram_range: [1,2]
model_output:
  base_model: 'model/base_model.pkl'
  good_model: 'model/good_model.pkl'
  vectorizer: 'model/vectorizer.pkl'
