data_input:
  all_data: 'data/raw/all-data.csv'
data_interim:
data_output:
model_input:
model_output:
  base_model: 'model/base_model.pkl'
  good_model: 'model/good_model.pkl'
reproducibility:
  rnd_seed: 21
